#!/bin/bash

docker run \
  --rm \
  -w /app \
  -v $(pwd):/app \
  -p 3000:3000 \
  -it \
  --network rebase-challenge \
  ruby \
  bash -c "gem install rack sinatra puma pg rspec redis sidekiq && apt update && apt install postgresql-client -y && bash"
